//
//  MYAssets.swift
//
//  Generated by CodeGen (by Some1)
//  Copyright © 2019 GMO-Z.com RunSystem. All rights reserved.
//
//  THIS FILE IS AUTO-GENERATED. DO NOT EDIT!

import UIKit

/// Image assets from 'myProject/Resources/Assets.xcassets'
struct MYAssets {

    struct Icon {

        static var xcode: UIImage {
            return #imageLiteral(resourceName: "xcode")
        }

    }

}
