//
//  MYText.swift
//
//  Generated by CodeGen (by Some1)
//  Copyright © 2018 GMO-Z.com RunSystem. All rights reserved.
//
//  THIS FILE IS AUTO-GENERATED. DO NOT EDIT!
//  Add text key & content into Localizable.strings and Build project.

import Foundation

extension String {

    struct MYLocalizable {

        /**
         attr_2param_text
         - vi: "\<b\>%@\</b\>\<i\>\</i\>"
         - Base: "\<b\>%@\</b\>\<i\>%@\</i\>"
        */
        static func attr2ParamText(_ param1: Any, _ param2: Any) -> NSAttributedString {
            let pattern = NSLocalizedString("attr_2param_text", tableName: "Localizable", comment: "")
            let htmlString = String(format: pattern, "\(param1)", "\(param2)")
            return makeAttributeString(htmlString)
        }

        /**
         attr_bold_text
         - Base: "\<b\>Bold text\</b\>\""
        */
        static var attrBoldText: NSAttributedString {
            let htmlString = NSLocalizedString("attr_bold_text", tableName: "Localizable", comment: "")
            return makeAttributeString(htmlString)
        }

        /**
         attr_param_text
         - Base: "\<b\>%@\</b\>\""
        */
        static func attrParamText(_ param1: Any) -> NSAttributedString {
            let pattern = NSLocalizedString("attr_param_text", tableName: "Localizable", comment: "")
            let htmlString = String(format: pattern, "\(param1)")
            return makeAttributeString(htmlString)
        }

        /**
         normal text
         - vi: "Văn bản\n bềnh thường"
         - Base: "Normal\n text 1"
        */
        static var normalText: String {
            return NSLocalizedString("normal text", tableName: "Localizable", comment: "")
        }

        /**
         normal text 1
         - Base: "Normal text"
        */
        static var normalText1: String {
            return NSLocalizedString("normal text 1", tableName: "Localizable", comment: "")
        }

        /**
         param text
         - Base: "Param: %@"
        */
        static func paramText(_ param1: Any) -> String {
            let pattern = NSLocalizedString("param text", tableName: "Localizable", comment: "")
            return String(format: pattern, "\(param1)")
        }

        private static func makeAttributeString(_ htmlString: String) -> NSAttributedString {
            if let data = htmlString.data(using: .utf8),
                let result = try? NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html,
                                                                           .characterEncoding: NSNumber(value: String.Encoding.utf8.rawValue)],
                                                     documentAttributes: nil) {
                return result
            }
            return NSAttributedString()
        }

    }

}
